import React from 'react';
import { Container, Heading, Text, Box } from '@radix-ui/themes';

const TermsOfService = () => {
  return (
    <Container size="3" px="4" className="font-body">
      <Box my="6">
        <Heading size="8" weight="bold" className="font-interface mb-4">
          Terms of Service
        </Heading>
        <Text as="p" size="3" className="text-medium-gray mb-6">
          These Terms of Service (the "Terms") govern your access to and use of the websites, applications, bots, and
          related services offered by Traken AI ("Traken AI", "we", "us", or "our"), including our Telegram chatbot and
          any subscription features (collectively, the "Services"). By accessing or using the Services, you agree to be
          bound by these Terms. If you do not agree, do not use the Services.
        </Text>

        <Heading size="5" className="font-interface mb-2">1. Who We Are</Heading>
        <Text as="p" size="3" className="text-medium-gray mb-4">
          Traken AI provides AI-powered market intelligence, insights, and tools designed to assist users in researching
          and monitoring digital assets and markets. We are based in Los Angeles County, California. Contact us at
          <a className="text-traken-violet underline" href="mailto:contact@traken.xyz"> contact@traken.xyz</a>.
        </Text>

        <Heading size="5" className="font-interface mb-2">2. Eligibility</Heading>
        <Text as="p" size="3" className="text-medium-gray mb-4">
          You must be at least 18 years old and legally capable of entering into a binding contract to use the Services.
          You may not use the Services if you are located in, under the control of, or a national or resident of any
          country subject to U.S. sanctions, or if you are listed on any U.S. government denied-party list.
        </Text>

        <Heading size="5" className="font-interface mb-2">3. Account, Security, and Acceptable Use</Heading>
        <Text as="p" size="3" className="text-medium-gray mb-4">
          You are responsible for all activity that occurs under your accounts (including third‑party messaging accounts)
          used to access the Services. Maintain the confidentiality of your credentials and notify us promptly of any
          unauthorized use. You agree not to: (a) reverse engineer, modify, or create derivative works of the Services;
          (b) bypass or breach security or rate limits; (c) use the Services for unlawful, infringing, deceptive,
          fraudulent, or harmful purposes; (d) upload or transmit malware; (e) harvest or collect information without
          consent; (f) spam, harass, or interfere with other users; or (g) use the Services to provide or receive
          unlicensed investment, legal, tax, or other regulated advice.
        </Text>

        <Heading size="5" className="font-interface mb-2">4. AI and Market Information — No Advice</Heading>
        <Text as="p" size="3" className="text-medium-gray mb-4">
          Outputs generated by the Services, including buy/sell/hold signals, insights, alerts, recommendations, and
          summaries, are provided for informational and educational purposes only and do not constitute financial,
          investment, legal, or tax advice. You are solely responsible for evaluating information and making independent
          decisions. Markets are volatile and past performance does not guarantee future results. Traken AI is not a
          broker, dealer, investment adviser, or fiduciary, and does not execute trades on your behalf unless explicitly
          stated in a separate signed agreement.
        </Text>

        <Heading size="5" className="font-interface mb-2">5. Subscriptions, Billing, and Refunds</Heading>
        <Text as="p" size="3" className="text-medium-gray mb-4">
          Certain features require a paid subscription. If you enroll, you authorize us (and our payment processors) to
          charge the applicable fees, taxes, and any currency conversion costs to your chosen payment method on a
          recurring basis until you cancel. Subscriptions renew automatically at the end of each term unless you cancel
          before renewal via the method provided in your account or the platform used for subscription management. Except
          where required by law or expressly stated otherwise, fees are non‑refundable and non‑transferable. We may change
          prices upon advance notice for future billing cycles.
        </Text>

        <Heading size="5" className="font-interface mb-2">6. Payments in Digital Assets</Heading>
        <Text as="p" size="3" className="text-medium-gray mb-4">
          Where permitted, you may pay using cryptocurrencies or tokens. Digital asset transactions are irreversible and
          may be subject to network fees and exchange rate volatility. You are responsible for ensuring you send funds to
          the correct address, selecting appropriate network parameters, and bearing all on‑chain risks. Discounts or
          benefits for using any token are promotional and may change or terminate at any time.
        </Text>

        <Heading size="5" className="font-interface mb-2">7. Tokens, Revenue Share, and Promotions</Heading>
        <Text as="p" size="3" className="text-medium-gray mb-4">
          Any references to tokens, revenue sharing, buy‑and‑burn mechanisms, or similar features relate to prospective or
          promotional programs and do not constitute an offer or solicitation of securities or any other regulated
          instrument. Participation may be limited by applicable law and may require additional terms. Benefits are not
          guaranteed and may be modified, suspended, or discontinued at our discretion and/or as required to comply with
          laws and regulations.
        </Text>

        <Heading size="5" className="font-interface mb-2">8. Third‑Party Services</Heading>
        <Text as="p" size="3" className="text-medium-gray mb-4">
          The Services may integrate with, reference, or link to third‑party services (including exchanges, wallets,
          analytics, messaging apps, and content). We do not control and are not responsible for third‑party services, and
          your use of them is governed by their terms and privacy policies. We are not liable for third‑party failures,
          data loss, or changes.
        </Text>

        <Heading size="5" className="font-interface mb-2">9. Intellectual Property</Heading>
        <Text as="p" size="3" className="text-medium-gray mb-4">
          We and our licensors own all rights, title, and interest in and to the Services and all related content and
          technology, including the trademarks, logos, text, graphics, interfaces, and software. Subject to your
          compliance with these Terms, we grant you a limited, non‑exclusive, non‑transferable, non‑sublicensable, and
          revocable license to access and use the Services for your personal or internal business purposes. We reserve all
          rights not expressly granted.
        </Text>

        <Heading size="5" className="font-interface mb-2">10. User Content and Feedback</Heading>
        <Text as="p" size="3" className="text-medium-gray mb-4">
          If you submit data, prompts, messages, content, or feedback, you grant us a worldwide, royalty‑free, perpetual,
          irrevocable, sublicensable license to use, host, reproduce, modify, adapt, publish, translate, create
          derivative works from, and display such content for operating, improving, and promoting the Services. You
          represent that you have the necessary rights to grant this license and that your content does not infringe the
          rights of others or violate law.
        </Text>

        <Heading size="5" className="font-interface mb-2">11. Compliance, Taxes, and Export Controls</Heading>
        <Text as="p" size="3" className="text-medium-gray mb-4">
          You are solely responsible for compliance with applicable laws (including trading, data protection, anti‑spam,
          consumer, and financial regulations) and for all taxes or duties arising from your use of the Services. You
          agree to comply with U.S. export control and sanctions laws, including those administered by OFAC and BIS, and
          not to export or re‑export the Services to prohibited jurisdictions or parties.
        </Text>

        <Heading size="5" className="font-interface mb-2">12. Disclaimers</Heading>
        <Text as="p" size="3" className="text-medium-gray mb-4">
          THE SERVICES ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE
          DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
          PARTICULAR PURPOSE, TITLE, AND NON‑INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF
          TRADE. WE DO NOT WARRANT THAT THE SERVICES WILL BE ACCURATE, RELIABLE, UNINTERRUPTED, TIMELY, SECURE, OR ERROR‑
          FREE, OR THAT DEFECTS WILL BE CORRECTED.
        </Text>

        <Heading size="5" className="font-interface mb-2">13. Limitation of Liability</Heading>
        <Text as="p" size="3" className="text-medium-gray mb-4">
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT WILL TRAKEN AI OR ITS AFFILIATES, OFFICERS, DIRECTORS,
          EMPLOYEES, AGENTS, OR PARTNERS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR
          EXEMPLARY DAMAGES, OR ANY LOSS OF PROFITS, REVENUE, DATA, OR GOODWILL, ARISING OUT OF OR IN CONNECTION WITH THE
          SERVICES OR THESE TERMS, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. OUR TOTAL LIABILITY FOR ALL CLAIMS
          RELATING TO THE SERVICES SHALL NOT EXCEED THE GREATER OF: (A) THE AMOUNT YOU PAID TO US FOR THE SERVICES IN THE
          SIX (6) MONTHS PRECEDING THE EVENT GIVING RISE TO THE CLAIM; OR (B) ONE HUNDRED U.S. DOLLARS (US$100).
        </Text>

        <Heading size="5" className="font-interface mb-2">14. Indemnification</Heading>
        <Text as="p" size="3" className="text-medium-gray mb-4">
          You will indemnify, defend, and hold harmless Traken AI and its affiliates, officers, directors, employees, and
          agents from and against any claims, liabilities, damages, losses, and expenses (including reasonable attorneys'
          fees) arising out of or related to: (a) your use of the Services; (b) your violation of these Terms; (c) your
          content; or (d) your violation of any law or the rights of a third party.
        </Text>

        <Heading size="5" className="font-interface mb-2">15. Dispute Resolution, Arbitration, and Venue</Heading>
        <Text as="p" size="3" className="text-medium-gray mb-4">
          Please read this section carefully. It affects your rights.
        </Text>
        <Text as="p" size="3" className="text-medium-gray mb-4">
          You and Traken AI agree that any dispute, claim, or controversy arising out of or relating to these Terms or the
          Services shall be resolved exclusively and finally by binding arbitration administered by JAMS pursuant to its
          Streamlined Arbitration Rules and Procedures, or, if JAMS is unavailable, by the American Arbitration
          Association under its Consumer Arbitration Rules. The arbitration will be conducted in Los Angeles County,
          California, in English, by a single arbitrator. Judgment on the award may be entered in any court of competent
          jurisdiction. This arbitration agreement shall be interpreted broadly.
        </Text>
        <Text as="p" size="3" className="text-medium-gray mb-4">
          CLASS ACTION WAIVER: YOU AND TRAKEN AI AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS
          INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING.
          UNLESS BOTH YOU AND TRAKEN AI AGREE, THE ARBITRATOR MAY NOT CONSOLIDATE MORE THAN ONE PERSON'S CLAIMS OR
          OTHERWISE PRESIDE OVER ANY FORM OF A REPRESENTATIVE OR CLASS PROCEEDING.
        </Text>
        <Text as="p" size="3" className="text-medium-gray mb-4">
          Opt‑Out: You may opt out of this arbitration agreement by sending written notice to
          <a className="text-traken-violet underline" href="mailto:contact@traken.xyz"> contact@traken.xyz</a> within 30
          days of first accepting these Terms. If you opt out, or if this arbitration agreement is found unenforceable,
          then the exclusive jurisdiction and venue for any action shall be the state and federal courts located in Los
          Angeles County, California, and you consent to the personal jurisdiction of such courts.
        </Text>

        <Heading size="5" className="font-interface mb-2">16. California Disclosures</Heading>
        <Text as="p" size="3" className="text-medium-gray mb-4">
          Under California Civil Code § 1789.3, you may contact the Complaint Assistance Unit of the Division of
          Consumer Services of the California Department of Consumer Affairs in writing at 1625 North Market Blvd., Suite
          N‑112, Sacramento, CA 95834, or by telephone at (800) 952‑5210, to resolve a complaint regarding the Services.
        </Text>

        <Heading size="5" className="font-interface mb-2">17. Modifications and Suspension</Heading>
        <Text as="p" size="3" className="text-medium-gray mb-4">
          We may modify these Terms or the Services at any time. If we make material changes, we will provide notice by
          posting the updated Terms on our website or through the Services, and updating the "Last Updated" date. Changes
          become effective when posted unless stated otherwise. We may suspend or terminate the Services (in whole or in
          part) at any time, including for maintenance, upgrades, or to comply with law.
        </Text>

        <Heading size="5" className="font-interface mb-2">18. Termination</Heading>
        <Text as="p" size="3" className="text-medium-gray mb-4">
          You may stop using the Services at any time. We may terminate or suspend your access immediately for any reason,
          including if we believe you have violated these Terms or pose a risk to others, or as required by law. Upon
          termination, sections that by their nature should survive (including ownership, disclaimers, limitation of
          liability, indemnification, dispute resolution, and governing law) will survive.
        </Text>

        <Heading size="5" className="font-interface mb-2">19. Governing Law</Heading>
        <Text as="p" size="3" className="text-medium-gray mb-4">
          These Terms and any dispute arising out of or related to them are governed by the laws of the State of
          California, without regard to its conflict of laws principles, and applicable federal law, except to the extent
          preempted by arbitration law as set forth above.
        </Text>

        <Heading size="5" className="font-interface mb-2">20. Miscellaneous</Heading>
        <Text as="p" size="3" className="text-medium-gray mb-4">
          These Terms constitute the entire agreement between you and Traken AI regarding the Services and supersede any
          prior agreements. If any provision is found unenforceable, the remaining provisions will remain in full force.
          Our failure to enforce any right is not a waiver. You may not assign these Terms without our prior written
          consent. We may assign these Terms in connection with a merger, acquisition, or sale of assets.
        </Text>

        <Text as="p" size="2" className="text-dim-gray mt-8">
          Last Updated: August 2025
        </Text>
      </Box>
    </Container>
  );
};

export default TermsOfService;


